name: TigerPig
favicon: null
layout_spectrum: 0.985564045375213
typography_spectrum: 0.9715110501274467
title: Tiger Pig Media Development and Production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8d867c'
    - '#ffffff'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.4318364099599421
  lightness: 0.9859071501996368
  saturation: 0.4871606563683599
  rhythmicContrast: 0.005211651558056474
purpose: []
