name: TigerPig
favicon: null
layout_spectrum: 0.985564045375213
typography_spectrum: 0.9715110501274467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4318364099599421
  lightness: 0.9859071501996368
  saturation: 0.4871606563683599
  rhythmicContrast: 0.005211651558056474
purpose: []
